{
  "name": "durandal/amd/almond-custom",
  "inlineText": true,
  "stubModules": [
    "durandal/amd/text"
  ],
  "paths": {
    "text": "durandal/amd/text"
  },
  "baseUrl": "C:\\DNNDev.me\\DesktopModules\\Framework\\App",
  "mainConfigFile": "C:\\DNNDev.me\\DesktopModules\\Framework\\App\\main.js",
  "include": [
    "config",
    "text!dareAdd.html",
    "dareAdd",
    "text!dareDetail.html",
    "dareDetail",
    "text!dareList.html",
    "dareList",
    "dataService",
    "dataServiceHelper",
    "enums",
    "text!home.html",
    "home",
    "text!index.html",
    "text!loader.html",
    "logger",
    "main-built",
    "main",
    "text!menu.html",
    "text!navbar.html",
    "text!profile.html",
    "profile",
    "text!shell.html",
    "shell",
    "uiutilities",
    "viewModelHelper",
    "durandal/app",
    "durandal/composition",
    "durandal/events",
    "durandal/http",
    "text!durandal/messageBox.html",
    "durandal/messageBox",
    "durandal/modalDialog",
    "durandal/system",
    "durandal/viewEngine",
    "durandal/viewLocator",
    "durandal/viewModel",
    "durandal/viewModelBinder",
    "durandal/widget",
    "durandal/plugins/router",
    "durandal/transitions/entrance",
    "js/cordova",
    "js/facebookscript",
    "lib/jquery-2.0.0.intellisense",
    "lib/jquery-2.0.0",
    "lib/jquery-2.0.0.min",
    "lib/knockout-2.2.1.debug",
    "lib/knockout-2.2.1",
    "lib/ratchet",
    "lib/sammy-0.7.4",
    "lib/sammy-0.7.4.min"
  ],
  "exclude": [],
  "keepBuildDir": true,
  "optimize": "uglify2",
  "out": "C:\\DNNDev.me\\DesktopModules\\Framework\\App\\main-built.js",
  "pragmas": {
    "build": true
  },
  "wrap": true,
  "insertRequire": [
    "main"
  ]
}